name: Valist
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - uses: valist-io/valist-github-action@v2.2.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: nftsafelaunch
          project: example
          release: ${{ env.TIMESTAMP }}
          files: '**'
